import { Config } from '@stencil/core';
import { reactOutputTarget as react } from '@stencil/react-output-target';

export const config: Config = {
  namespace: 'atombomb',
  outputTargets: [
    react({
      // name of the Stencil Component Library
      componentCorePackage: 'atombomb',
      // This file gets generated by React wrapper function and contains definitions of all Wrapper components
      proxiesFile: './src/index.ts',
      includeDefineCustomElements: true,
    }),
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
      generateTypeDeclarations: true
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};
